name: Build Multiarch Base Image

on:
  workflow_dispatch:
  # Optionally trigger on changes to Dockerfile.base:
  # push:
  #   paths:
  #     - Dockerfile.base

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multiarch base image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.base
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/base:latest
